// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzWin6colJBD2C1VJmujAutHqFHEjIMLs',
    appId: '1:824343242821:web:b96274e9be90213a3b1b2c',
    messagingSenderId: '824343242821',
    projectId: 'flutter-fp-84f54',
    authDomain: 'flutter-fp-84f54.firebaseapp.com',
    databaseURL: 'https://flutter-fp-84f54-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-fp-84f54.appspot.com',
    measurementId: 'G-Q0P77884ZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFIJ9Hpo7SRhcsdV70JdNT6Dfj9wkFSio',
    appId: '1:824343242821:android:d88f1675e6bb23ed3b1b2c',
    messagingSenderId: '824343242821',
    projectId: 'flutter-fp-84f54',
    databaseURL: 'https://flutter-fp-84f54-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-fp-84f54.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnKV7PbQT13sWH62br4XWRhbI6hc8BR7g',
    appId: '1:824343242821:ios:85d65c7e7452a6e03b1b2c',
    messagingSenderId: '824343242821',
    projectId: 'flutter-fp-84f54',
    databaseURL: 'https://flutter-fp-84f54-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-fp-84f54.appspot.com',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnKV7PbQT13sWH62br4XWRhbI6hc8BR7g',
    appId: '1:824343242821:ios:85d65c7e7452a6e03b1b2c',
    messagingSenderId: '824343242821',
    projectId: 'flutter-fp-84f54',
    databaseURL: 'https://flutter-fp-84f54-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-fp-84f54.appspot.com',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzWin6colJBD2C1VJmujAutHqFHEjIMLs',
    appId: '1:824343242821:web:c3ff934ccd0a70f73b1b2c',
    messagingSenderId: '824343242821',
    projectId: 'flutter-fp-84f54',
    authDomain: 'flutter-fp-84f54.firebaseapp.com',
    databaseURL: 'https://flutter-fp-84f54-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-fp-84f54.appspot.com',
    measurementId: 'G-X0TPSXSYTZ',
  );
}
